# This is a basic workflow to help you get started with Actions

name: Publish to NuGet

# Controls when the workflow will run
on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  package:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Restore NuGet Packages
        run: nuget restore Archipelago.MultiClient.Net.sln
        
      - name: Build Library
        run: msbuild Archipelago.MultiClient.Net.sln /property:Configuration=Release
        
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Creating NuGet Package
        run: nuget pack Archipelago.MultiClient.Net.nuspec -Version "${{ env.TAG }}"

      - name: Releasing to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGETAPIKEY }}
        run: dotnet nuget push "Archipelago.MultiClient.Net.${{ env.TAG }}.nupkg" --source https://api.nuget.org/v3/index.json --api-key "$env:NUGET_API_KEY"
